// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: address.proto

package model;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.Address)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string house = 1;</code>
   * @return The house.
   */
  java.lang.String getHouse();
  /**
   * <code>string house = 1;</code>
   * @return The bytes for house.
   */
  com.google.protobuf.ByteString
      getHouseBytes();

  /**
   * <code>string street = 2;</code>
   * @return The street.
   */
  java.lang.String getStreet();
  /**
   * <code>string street = 2;</code>
   * @return The bytes for street.
   */
  com.google.protobuf.ByteString
      getStreetBytes();

  /**
   * <code>string city = 3;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>string city = 3;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string postalCode = 4;</code>
   * @return The postalCode.
   */
  java.lang.String getPostalCode();
  /**
   * <code>string postalCode = 4;</code>
   * @return The bytes for postalCode.
   */
  com.google.protobuf.ByteString
      getPostalCodeBytes();

  /**
   * <code>string country = 5;</code>
   * @return The country.
   */
  java.lang.String getCountry();
  /**
   * <code>string country = 5;</code>
   * @return The bytes for country.
   */
  com.google.protobuf.ByteString
      getCountryBytes();
}
