// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package model;

public interface CustomerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.Customer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstName = 1;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 1;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string secondName = 2;</code>
   * @return The secondName.
   */
  java.lang.String getSecondName();
  /**
   * <code>string secondName = 2;</code>
   * @return The bytes for secondName.
   */
  com.google.protobuf.ByteString
      getSecondNameBytes();

  /**
   * <code>int32 age = 3;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>.model.Address address = 5;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.model.Address address = 5;</code>
   * @return The address.
   */
  model.Address getAddress();
  /**
   * <code>.model.Address address = 5;</code>
   */
  model.AddressOrBuilder getAddressOrBuilder();
}
